name: Test Workflow

on:
  push:
    branches: [ master ]

jobs:

  check:
    runs-on: self-hosted

    strategy:
      matrix:
        version: [1]

    steps:
      - uses: actions/checkout@v4

      - name: Check files
        run: |
          if [ ! -f test.sh ]; then
            echo "missing test.sh" > napaka.txt
          else
            echo "" > napaka.txt
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: napaka
          path: napaka.txt


  test:
    needs: check
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: napaka

      - name: Check error
        run: |
          if [ -s napaka.txt ]; then
            echo "FAIL"
            exit 1
          fi

      - name: Run tests
        run: |
          chmod +x test.sh
          ./test.sh
