name: Test Workflow

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Dovoli izvajanje skripte
        run: chmod +x test.sh

      - name: Zaženi teste
        run: ./test.sh
